language: python
python:
- "3.6"
- "3.7"

env:
- DB=redis
- DB=mysql

before_install: skip

install:
- pip install pipenv
- pipenv install

before_script: skip

script:
    - pipenv run python ./tests/test_demo.py

after_success: skip

after_failure: skip

before_deploy: skip

deploy: skip

after_deploy: skip

after_script: skip